/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleEditor: typeof import('./components/ArticleEditor.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VinlandAdminCard: typeof import('./components/VinlandAdminCard.vue')['default']
    VinlandAdminMenu: typeof import('./components/VinlandAdminMenu.vue')['default']
    VinlandArchiveCard: typeof import('./components/VinlandArchiveCard.vue')['default']
    VinlandBackToTop: typeof import('./components/VinlandBackToTop.vue')['default']
    VinlandButton: typeof import('./components/VinlandButton.vue')['default']
    VinlandCard: typeof import('./components/VinlandCard.vue')['default']
    VinlandCatalogCard: typeof import('./components/VinlandCatalogCard.vue')['default']
    VinlandCategoryCard: typeof import('./components/VinlandCategoryCard.vue')['default']
    VinlandCover: typeof import('./components/VinlandCover.vue')['default']
    VinlandDivider: typeof import('./components/VinlandDivider.vue')['default']
    VinlandFooter: typeof import('./components/VinlandFooter.vue')['default']
    VinlandFormCard: typeof import('./components/VinlandFormCard.vue')['default']
    VinlandHeader: typeof import('./components/VinlandHeader.vue')['default']
    VinlandHotArticleCard: typeof import('./components/VinlandHotArticleCard.vue')['default']
    VinlandLightBox: typeof import('./components/VinlandLightBox.vue')['default']
    VinlandPostArticleCard: typeof import('./components/VinlandPostArticleCard.vue')['default']
    VinlandTagCard: typeof import('./components/VinlandTagCard.vue')['default']
    VinlandUploader: typeof import('./components/VinlandUploader.vue')['default']
    VinlandWifeCover: typeof import('./components/VinlandWifeCover.vue')['default']
    VinlandWorldCloudCard: typeof import('./components/VinlandWorldCloudCard.vue')['default']
  }
}
